app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace='todo')),
]

app/todo/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

app_name = 'todo'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='todo:login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', TaskDelete.as_view(), name='task-delete'),
]

app/todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete']

app/todo/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .models import Task


class CustomLoginView(LoginView):
    template_name = 'todo/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('todo:tasks')


class RegisterPage(FormView):
    template_name = 'todo/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('todo:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('todo:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__contains=search_input)

        context['search_input'] = search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'todo/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('todo:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('todo:tasks')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todo:tasks')

app/todo/templates/todo/login.html
<h1>Login</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Login">
</form>


<p>Don't have an account? <a href="{% url 'todo:register' %}">Register</a> </p>

app/todo/templates/todo/register.html
<h1>Register</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Login">
</form>


<p>Already have an account? <a href="">Login</a> </p>

app/todo/templates/todo/task.html
<h1>Task: {{ task }}</h1>
<a href="{% url 'todo:tasks' %}">Go back</a>

app/todo/templates/todo/task_confirm_delete.html
<a href="{% url 'todo:tasks' %}">Go back</a>
<form method="POST">
  {% csrf_token %}
  <p>Are your sure you want to delete this task? "{{ task }}"</p>
  <input type="submit" value="Delete"/>
</form>

app/todo/templates/todo/task_form.html
<h3>Task Form</h3>
<a href="{% url 'todo:tasks' %}">Go back</a>

<form method="POST" action="">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>

app/todo/templates/todo/task_list.html
{% if request.user.is_authenticated %}
    <p>{{ request.user }}</p>
    <a href="{% url 'todo:logout' %}">Logout</a>
{% else %}
<a href="{% url 'todo:login' %}">Login</a>
{% endif %}

<hr>
<h1>My TO DO List {{ color }}</h1>

<a href="{% url 'todo:task-create' %}">Add Task</a>

<form method="GET">
    <input type="text" name="search-area" value="{{ search_input }}">
    <input type="submit" value="Search">

</form>

<table>
    <tr>
        <th>Item</th>
        <th></th>
        <th></th>
    </tr>
    {% for task in tasks %}
    <tr>
        <td>{{ task.title }}</td>
        <td><a href="{% url 'todo:task' task.id %}">View</a></td>
        <td><a href="{% url 'todo:task-update' task.id %}">Edit</a></td>
        <td><a href="{% url 'todo:task-delete' task.id %}">Delete</a></td>
    </tr>
    {% empty %}
        <h3>No items in list</h3>
    {% endfor %}
</table>